### ISSUE TITLE
Add more options to the interactive mode.

### ISSUE THREAD

**Issue by hvdklauw** [darrikonn/td-cli#1]
- [x] Add todo
- [x] Edit Todo
- [x] Delete todo

I think that would make going through your list, cleaning it and adding tasks for the day a much nicer experience.

**Comment by darrikonn** [comment]
Good suggestion 👍. I'll add that.

**Comment by darrikonn** [comment]
Done! Implemented in version 1.0.0. Upgrade td-cli ;)
