### ISSUE TITLE
OSError when piping 

### ISSUE THREAD

**Issue by Austreelis** [darrikonn/td-cli#10]
When piping the output of `td`, a call to `os.get_terminal_size()` raises an `OSError` that is never caucht:

![image](https://user-images.githubusercontent.com/56743515/69261716-64beac80-0bc2-11ea-8531-0fee11e5229b.png)
![image](https://user-images.githubusercontent.com/56743515/69261889-b9fabe00-0bc2-11ea-9fe8-bf5a918817f1.png)

Demonstration with a little snippet:

```python
import os
print("foo")
print(os.get_terminal_size())
```

This works fine when running the script, but running `python example.py | grep foo` throws:

```
Traceback (most recent call last):
  File "/tmp/example.py", line 5, in <module>
    print(os.get_terminal_size())
foo
OSError: [Errno 25] Inappropriate ioctl for device
```

---

This looks quite easy to solve, so I already forked and will start working on it asap.
FYI, I am trying to display my todos in conky, using [this project](https://github.com/pawamoy/ansito) to convert ansi color codes to conky color commands by piping  `td` into `ansito -`, and give that to conky to display as text.

**Comment by darrikonn** [comment]
Ah nice! Thanks for submitting the issue.

I made the fix in https://github.com/darrikonn/td-cli/pull/11/files -> so you can upgrade td-cli with `pip install --upgrade td-cli`. Version `1.2.4` contains the fix :).

Thanks again!
