### ISSUE TITLE
Interactive td-cli quits after resume pushing any arrow button

### ISSUE THREAD

**Issue by p3k** [darrikonn/td-cli#25]
If I do this:

1. Run `td -i`
2. Suspend with `^Z`
3. Resume with `fg`
4. Press arrow down button ↓ to select next entry

– then td-cli simply quits and I need to restart it.

Not sure if this is an effect of my setup, would be glad if someone could verify / try to reproduce.

**Comment by darrikonn** [comment]
Yuup, happens to me as well. I only use the vim keybindings (hjkl), so I haven't seen this before :). Doesn't happen with hjkl.

Will fix it!
Thanks for the issue.

**Comment by p3k** [comment]
well, thank you for td-cli and your swift reply.

**Comment by darrikonn** [comment]
Spent some time debugging this and I believe this is an issue with Python Curses.
After resuming a suspended task, the arrow keys indeed return the `escape` character from Python Curses which `td-cli` correctly interprets as exiting the interactive mode.

I currently don't have time to take this further. The next steps would be to file an issue with Python Curses regarding the `stdscr.getch()` + `arrow keys` + `resuming fg` = `escape (27)`.

**Comment by p3k** [comment]
i see, seems to be a rabbit hole… if i find the time i am going to take a look at the python curses repo and maybe file an issue.

in the meantime i am training my muscle memory with the vim keybindings :muscle:

**Comment by darrikonn** [comment]
> i see, seems to be a rabbit hole… if i find the time i am going to take a look at the python curses repo and maybe file an issue.
> 
> in the meantime i am training my muscle memory with the vim keybindings 💪

Awesome, thanks!
Lol, yeah the vim keybindings take time to adjust :).

**Comment by darrikonn** [comment]
I've submitted an issue for this:
https://bugs.python.org/issue43854

**Comment by p3k** [comment]
great! i took a coarse look yesterday but was not sure whether i am capable of providing the necessary information. glad you did now :) cheers.

**Comment by darrikonn** [comment]
Closing this one since td-cli can't fix it (needs to be resolved by curses)
