### ISSUE TITLE
Two small tweaks for the new interactive mode.

### ISSUE THREAD

**Issue by hvdklauw** [darrikonn/td-cli#4]
Thanks for implementing my suggested features in #1.

Tried it and loved it, great addition.

There are however two small things I noticed.

- [x] Can't add anymore when I deleted everything, the option goes away, there is only recover and quit.
- [x] Can't start interactive mode if there are no todo's

I think everything else is fine

**Comment by darrikonn** [comment]
Aah, you're right!

After adding the 'add' feature, the interactive mode should always be available!

Thanks for these feedbacks, they are awesome!

Will see if I can squeeze this into my schedule tomorrow!

**Comment by darrikonn** [comment]
Finished implementing this! Available in version 1.1.0 :+1: 

Thanks again!
